
  CREATE TABLE "CASA_O"."VOLUNTEER" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PINCODE" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"MOBILE_NUMBER" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"LAND_PHONE" VARCHAR2(15 BYTE), 
	"EMERGENCY_NUMBER" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"RELATION_EMRGNCY_CNTCT" VARCHAR2(100 BYTE), 
	"EMAIL_ID" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"REASON_FOR_VOLUNTEERING" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"PREVIOUS_EXPERIENCES" VARCHAR2(2000 BYTE), 
	"AVILABILITY_WEEK_HRS" VARCHAR2(100 BYTE), 
	"AVILABLTY_DAYS" VARCHAR2(200 BYTE), 
	"PREV_VOLUNTEER_JOBS" VARCHAR2(2000 BYTE), 
	"CALL_AT_WORK" VARCHAR2(5 BYTE), 
	"WORK_NUMBER" VARCHAR2(13 BYTE), 
	"EDUCATIONAL_EXPERIENCE" VARCHAR2(2000 BYTE), 
	"HOW_YOU_KNOW" VARCHAR2(500 BYTE), 
	"ADDITIONAL_INFO" VARCHAR2(2000 BYTE), 
	 CONSTRAINT "VOLUNTEER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  CREATE SEQUENCE  "CASA_O"."VOLUNTEER_SEQ"  MINVALUE 5001 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5001 CACHE 20 NOORDER  NOCYCLE ;


  CREATE OR REPLACE TRIGGER "CASA_O"."VOLUNTEER_TRG" BEFORE INSERT ON VOLUNTEER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.USER_ID IS NULL THEN
      SELECT VOLUNTEER_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CASA_O"."VOLUNTEER_TRG" ENABLE;
